language: go

go:
  - 1.10.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - DBUSER=postgres DBPASS=

services:
  - docker
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database testing;' -U postgres

script:
  - make test-coverage
  - make godep no-changes-in-commit

before_deploy:
  - make packages

deploy:
  go: 1.10.x
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - export DOCKER_PUSH_LATEST=$(echo ${TRAVIS_BRANCH} | grep -E '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$') || true
  - make docker-push
