[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  revision = "66bc47b361f027ec9666d9cffbf2e8acdc6d4f1f"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  name = "gopkg.in/src-d/framework.v0"
  revision = "bed6b25004fcbc1b034608f01d478aca4135b865"
  source = "https://github.com/src-d/framework.git"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"
  version = "4.2.0"

[[override]]
  name = "gopkg.in/src-d/go-billy-siva.v4"
  source = "https://github.com/src-d/go-billy-siva.git"
  version = "4.2.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  version = "4.5.0"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.4"

[[constraint]]
  name = "gopkg.in/src-d/go-queue.v1"
  version = "~1.0.2"

[prune]
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "gopkg.in/src-d/go-git-fixtures.v3"
    unused-packages = false
