[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  revision = "27a526a7da6f3e90812e390157c33c2dce445829"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  name = "gopkg.in/src-d/go-cli.v0"
  branch = "master"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"
  version = "4.3.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  version = "4.8.1"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.4"

[[constraint]]
  name = "gopkg.in/src-d/go-queue.v1"
  version = "~1.0.2"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "gopkg.in/src-d/go-billy-gluster.v0"
  revision = "a14b481441bb5ba7cba3c48cb3eb570f1c7fb5fd"

[[override]]
  name = "gopkg.in/src-d/go-billy-siva.v4"
  version = "4.2.1"

[prune]
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "gopkg.in/src-d/go-git-fixtures.v3"
    unused-packages = false
